version: '3'
services:
  postgres:
     image: postgres:latest
     container_name: postgres
     restart: unless-stopped
     volumes:
      - ./data/postgres:/var/lib/postgresql/data
     ports:
      - "5432:5432"
     environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    restart: unless-stopped
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
  traccar:
    image: traccar/traccar:latest
    container_name: traccar
    restart: unless-stopped
    volumes:
    - ./data/traccar/logs:/opt/traccar/logs:rw
    - ./data/traccar/data:/opt/traccar/data:rw
    - ./data/traccar/media:/opt/traccar/media:rw
    - ./conf/traccar/traccar.xml:/opt/traccar/conf/traccar.xml:ro
    ports:
    - "8082:8082"
    depends_on:
       - postgres

