micronaut:
  application:
    name: serviceStream
datasources:
  default:
    url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2
dataSource:
  url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
  driverClassName: org.h2.Driver
  username: sa
  password: ''
  pooled: true
  jmxExport: true
hibernate:
  hbm2ddl:
    auto: update
  cache:
    queries: false
    use_second_level_cache: false
    use_query_cache: false
elasticsearch.httpHosts: '"http://localhost:9200,http://127.0.0.2:9200"'
redis.uri: redis://localhost
jpa.default.properties.hibernate.hbm2ddl.auto: update
# cassandra:
#  default:
#    clusterName: '"myCluster"'
#    contactPoint: '"localhost"'
#    port: 9042
#    maxSchemaAgreementWaitSeconds: 20
#    ssl: true
# rabbitmq.uri: amqp://localhost:5672
